name: Docker

on:
  pull_request:
  workflow_dispatch:
  
jobs:
  terraform-actions:
    name: Workflow
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@master

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: public.ecr.aws/g4k5i3z6/yt-archiver
        ECR_IMAGE: yt-archiver
        IMAGE_TAG: latest 
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g4k5i3z6
        docker build -t yt-archiver .
        docker tag yt-archiver:latest public.ecr.aws/g4k5i3z6/yt-archiver:latest
        docker push public.ecr.aws/g4k5i3z6/yt-archiver:latest
