name: 'Terraform'
 
on:
  push:
    branches:
    - main
  pull_request:
 
jobs:
  terraform:
    name: 'Terraform'
    env:
      ENV_EXAMPLE: "TEST"
    runs-on: ubuntu-latest
    environment: test
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: 'Terraform Format'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.0.2
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: "./terraform"
         
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.0.2
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"
        args: '-backend-config="token=${{ secrets.TF_TOKEN }}" -backend-config="organization=samdowney"'

 
    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.0.2
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./terraform"
         
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.0.2
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "terraform"
        args: '-backend-config="token=${{ secrets.TF_TOKEN }}" -backend-config="organization=samdowney"'
 
    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main'
    #   uses: hashicorp/terraform-github-actions@master
    #   with:
    #     tf_actions_version: 1.0.2
    #     tf_actions_subcommand: 'applya'
    #     tf_actions_working_dir: "./terraform"
